CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  hash TEXT NOT NULL,
  recap INTEGER DEFAULT 1,
  remind INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY,
  uid INTEGER NOT NULL,
  title TEXT NOT NULL,
  done INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER PRIMARY KEY,
  email TEXT,
  message TEXT,
  created TEXT DEFAULT CURRENT_TIMESTAMP
);